### ISSUE TITLE
Switch to lowercase .pbo names

### ISSUE THREAD

**Issue by Schwaggot** [BlackOrderMod/BlackOrder#45]
Improvement/Feature request:
You might not know this, but on linux game servers it is difficult to work with .pbo names that have capital letters in them. Would be nice if the BlackOrder files could be renamed to all lowercase, e.g., BlackOrder_xXx.pbo --> blackorder_xxx.pbo

**Comment by ColdEvul** [comment]
Did not know this i will make the adjustment next release

**Comment by Schwaggot** [comment]
Thx, much appreciated! Btw, same goes for Addons and Keys folder -> addons/keys, not sure how it is currently in BlackOrder.
