### ISSUE TITLE
Error on A3 Launch

### ISSUE THREAD

**Issue by Siggyfreed** [BlackOrderMod/BlackOrder#86]
**Mod Version:** `2.1.4` 

**Description:**
- When launching game an error box indicates this mod requires addon 'rhs_main'. No such addon exists in the RHSUSAF mod and your code seems to already include the main file for the RHSUSAF mod.

**Comment by ColdEvul** [comment]
Thx for the report!

RHS might have renamed their `main` PBO.
I will take a look and see what's up here.

RHSUSAF is a requirement for the mod so as long as the mod is loaded you'll be fine.
The error is annoying but can be ignored if you have RHSUSAF loaded propperly.

Fix will be out later today if it is that that is the issue.

**Comment by ColdEvul** [comment]
Issue location:
https://github.com/BlackOrderMod/BlackOrder/blob/master/addons/main/config.cpp#L885
RHSAFRF?
